version: 2

models:
  - name: dim_listings_cleansed
    Description: cleaned Airbnb listings 
    columns:
      - name: listings_id
        Description: Primary key for listings
        tests:
          - unique
          - not_null

      - name: host_id
        Description: Referncing the host id with host table
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: minimum_nights
        Description: '{{ doc ("dim_listings_cleansed_mim_nights") }}'
        tests:
          - positive_values